import type { ContactType } from "@/schemas/contactSchema";

export const contacts: ContactType[] = [
  {
    id: "1",
    firstName: "Diego Alejandro",
    lastName: "Ruiz",
    email: "diegoruiz@adamo.com",
    countryCode: "+57",
    company: "-",
    position: "-",
    country: "-",
    cityRegion: "-",
  },
  {
    id: "2",
    firstName: "Laura",
    lastName: "Gonzalez",
    email: "laura.gonzalez@email.com",
    countryCode: "+34",
    company: "Tech Solutions",
    position: "Project Manager",
    country: "Spain",
    cityRegion: "Madrid",
  },
  {
    id: "3",
    firstName: "Juan",
    lastName: "Perez",
    email: "juanperez@company.com",
    countryCode: "+52",
    company: "Global Trade Co.",
    position: "Sales Representative",
    country: "Mexico",
    cityRegion: "CDMX",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Smith",
    email: "emily.smith@email.com",
    countryCode: "+1",
    company: "HealthPlus",
    position: "Nurse",
    country: "USA",
    cityRegion: "Los Angeles, CA",
  },
  {
    id: "5",
    firstName: "Ravi",
    lastName: "Kumar",
    email: "ravi.kumar@infotech.in",
    countryCode: "+91",
    company: "Infotech Pvt Ltd",
    position: "Software Engineer",
    country: "India",
    cityRegion: "Bangalore",
  },
  {
    id: "6",
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.martinez@email.com",
    countryCode: "+1",
    company: "Creative Design Hub",
    position: "Graphic Designer",
    country: "USA",
    cityRegion: "New York, NY",
  },
  {
    id: "7",
    firstName: "Omar",
    lastName: "Al-Farsi",
    email: "omar.alfarsi@commerce.com",
    countryCode: "+971",
    company: "Emirates Commerce",
    position: "Logistics Manager",
    country: "UAE",
    cityRegion: "Dubai",
  },
  {
    id: "8",
    firstName: "Nina",
    lastName: "Kowalski",
    email: "nina.kowalski@email.pl",
    countryCode: "+48",
    company: "FinTech Poland",
    position: "Financial Analyst",
    country: "Poland",
    cityRegion: "Warsaw",
  },
  {
    id: "9",
    firstName: "Chen",
    lastName: "Li",
    email: "chen.li@email.cn",
    countryCode: "+86",
    company: "Beijing Industries",
    position: "Operations Director",
    country: "China",
    cityRegion: "Beijing",
  },
  {
    id: "10",
    firstName: "Fatima",
    lastName: "Youssef",
    email: "fatima.youssef@email.ma",
    countryCode: "+212",
    company: "Atlas Consulting",
    position: "HR Manager",
    country: "Morocco",
    cityRegion: "Casablanca",
  },
];
